# dashboard/dashboard.py

# Placeholder or autogenerated content for dashboard/dashboard.py

import streamlit as st
import json
from agents.fetcher import fetch_nba_data
from agents.analyzer import analyze_game_data
from agents.summarizer import generate_summary
from agents.formatter import format_outputs
from agents.publisher import publish_all, fetch_thumbnail_url

st.set_page_config(page_title="NBA AI Content Dashboard", layout="wide")
st.title("🏀 NBA AI Content Pipeline")

if st.button("Run Full Pipeline"):
    with st.spinner("Fetching game data..."):
        game_data = fetch_nba_data()
    st.success("Data fetched")

    with st.spinner("Analyzing game data..."):
        analysis = analyze_game_data(game_data)
    st.success("Analysis complete")

    with st.spinner("Generating content..."):
        summary = generate_summary(analysis)
    st.success("Content generated")

    st.subheader("📝 Generated Summary")
    st.text_area("Headline", summary['headline'])
    st.text_area("Summary", summary['summary'])

    with st.spinner("Formatting for blog and socials..."):
        blog_html, twitter_text, insta_text = format_outputs(summary)
    st.success("Formatting complete")

    st.subheader("📄 Blog Preview")
    st.components.v1.html(blog_html, height=300)

    st.subheader("🐦 Twitter Preview")
    st.code(twitter_text, language='text')

    st.subheader("📸 Instagram Preview")
    st.code(insta_text, language='text')

    # Show highlight thumbnail preview
    with st.spinner("Fetching highlight thumbnail..."):
        thumbnail_url = fetch_thumbnail_url("NBA Highlights")
    if thumbnail_url:
        st.image(thumbnail_url, caption="Preview: Highlight Thumbnail", use_column_width=True)

    if st.button("Publish All"):
        publish_all(blog_html, twitter_text, insta_text)
        st.success("✅ Content published to all platforms!")
