# agents/analyzer.py

# Placeholder or autogenerated content for agents/analyzer.py

def analyze_game_data(game_data):
    if not game_data:
        return {}

    team1 = game_data["homeTeam"]
    team2 = game_data["awayTeam"]
    top_home = sorted(team1["players"], key=lambda p: p.get("points", 0), reverse=True)[:1]
    top_away = sorted(team2["players"], key=lambda p: p.get("points", 0), reverse=True)[:1]

    return {
        "home_team": team1["teamTricode"],
        "away_team": team2["teamTricode"],
        "home_score": team1["score"],
        "away_score": team2["score"],
        "top_performers": top_home + top_away
    }

