# agents/fetcher.py

# Placeholder or autogenerated content for agents/fetcher.py

from nba_api.live.nba.endpoints import scoreboard

def fetch_nba_data():
    games = scoreboard.ScoreBoard().get_dict()["scoreboard"]
    game_list = games.get("games", [])
    completed_games = [g for g in game_list if g.get("gameStatus") == 3]
    if completed_games:
        return completed_games[0]
    return {}
