# agents/fetcher.py

# Placeholder or autogenerated content for agents/fetcher.py

from nba_api.live.nba.endpoints import scoreboard, boxscore
import time

def fetch_nba_data():
    try:
        games = scoreboard.ScoreBoard().get_dict()["scoreboard"]["games"]
        completed = [g for g in games if g["gameStatus"] == 3]
        if not completed:
            return {}

        game_id = completed[0]["gameId"]
        time.sleep(1)  # avoid hitting rate limits
        full_data = boxscore.BoxScore(game_id=game_id).get_dict()
        return full_data
    except Exception as e:
        print("Error fetching NBA data:", e)
        return {}
