# agents/formatter.py

# Placeholder or autogenerated content for agents/formatter.py

def format_outputs(summary):
    if not summary:
        return "", "", ""

    blog_html = f"""
        <h2>{summary['headline']}</h2>
        <p><strong>Game Summary:</strong> {summary['summary']}</p>
        <p><em>Generated automatically using AI sports analytics.</em></p>
        <iframe src='https://www.youtube.com/embed?listType=search&list=NBA%20Highlights' width='100%' height='315'></iframe>
    """

    twitter_text = f"{summary['headline']}\n{summary['summary'].split('.')[0]}\n#NBA #GameRecap"
    insta_text = f"🔥 {summary['headline']}\n📊 {summary['summary'].split('.')[0]}\n🏀 Full Recap: {summary['summary']}\n#NBA #BasketballHighlights"

    return blog_html, twitter_text, insta_text
