OPENAI_API_KEY = "sk-..."
YOUTUBE_API_KEY = "AIza..."
WORDPRESS_URL = "https://yourblog.com"
WORDPRESS_USER = "admin"
WORDPRESS_APP_PASSWORD = "your_app_password"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAANEz2QEAAAAAWa%2BRhlHEr8%2F%2Bu4BWS%2BQ64PyF8Po%3DrA6gztLFEIWDVF7eRiEyeDgZxyiE3GJG0XVlxeNpMpUo36Zadk"
TWITTER_API_KEY = "KKXm1ZW5qgdH01khO2c3IhBvR"
TWITTER_API_SECRET = "kfoiQ5BpetPKtemfB048oXRjBSJZtQQTTshhI13iyUitgam0Ni"
TWITTER_ACCESS_TOKEN = "1930998810039214080-pI0kXxJl2EItVV5zgnANgOTurJeM1h"
TWITTER_ACCESS_SECRET = "RetLewf62Ol5BSC0kmSjaPDpoAmjHl94il02UMyOKliKG"
FACEBOOK_PAGE_ID = "645010945367907"
FACEBOOK_ACCESS_TOKEN = "EAAWRQ32tjDIBOZBwmbsg033ZAitiFoyMEYRu4NjGQxt1gscQpXzGwvtZBuT0FUtntZBuaDibhHZBhGzJtZCXUlI4Ix9qZCtr4ZBrmxZAMsUXVyB3Xjxfs1DptclK3e3ld9TDuZCuQv70HPGpnuyzhG5L7k7NfsSkRpKXi863nSV4ucdCHaZAdwfBOjjOYVGaHGdBrCPyZADdZBHWPidhCvTDkrOIZD"
INSTAGRAM_BUSINESS_ID = "1099678531989273"
THREADS_ACCESS_TOKEN = "threads_token"
