OPENAI_API_KEY = "sk-..."
YOUTUBE_API_KEY = "AIza..."
WORDPRESS_URL = "https://yourblog.com"
WORDPRESS_USER = "admin"
WORDPRESS_APP_PASSWORD = "your_app_password"
TWITTER_BEARER_TOKEN = "twitter_bearer_token"
FACEBOOK_PAGE_ID = "fb_page_id"
FACEBOOK_ACCESS_TOKEN = "fb_access_token"
INSTAGRAM_BUSINESS_ID = "ig_business_id"
THREADS_ACCESS_TOKEN = "threads_token"
