OPENAI_API_KEY = "sk-..."
YOUTUBE_API_KEY = "AIza..."
WORDPRESS_URL = "https://yourblog.com"
WORDPRESS_USER = "admin"
WORDPRESS_APP_PASSWORD = "your_app_password"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAANEz2QEAAAAAWa%2BRhlHEr8%2F%2Bu4BWS%2BQ64PyF8Po%3DrA6gztLFEIWDVF7eRiEyeDgZxyiE3GJG0XVlxeNpMpUo36Zadk"
TWITTER_API_KEY = "KKXm1ZW5qgdH01khO2c3IhBvR"
TWITTER_API_SECRET = "kfoiQ5BpetPKtemfB048oXRjBSJZtQQTTshhI13iyUitgam0Ni"
TWITTER_ACCESS_TOKEN = "1930998810039214080-pI0kXxJl2EItVV5zgnANgOTurJeM1h"
TWITTER_ACCESS_SECRET = "RetLewf62Ol5BSC0kmSjaPDpoAmjHl94il02UMyOKliKG"
FACEBOOK_PAGE_ID = "fb_page_id"
FACEBOOK_ACCESS_TOKEN = "IGAAJ3IEYtprtBZAFBkelhwTmswVHdwa2xXNjFldURMQk02U1h1TnF2WlB4dzBrMGxPMGFObThjd2QzX1JiQy0tNnBBX040T3hIR0k5X3N5M2lWbjBBbGUya1FkbEZAOMlVoWUF0MUlqemJDNjVYMVVxQVhqQkhCMlZAYd3hKX21UdwZDZD"
INSTAGRAM_BUSINESS_ID = "ig_business_id"
THREADS_ACCESS_TOKEN = "threads_token"
